name: Go

on:
  push:
  schedule:
    - cron: '42 2 * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      devnet:
        image: shardlabs/starknet-devnet:0.2.4
        ports:
        - 5050:5050

    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.18

    - name: wait for devnet to be up...
      run: ./.bin/devnet.sh

    - name: Test
      run: go test -v ./rpc/...
